import { prisma } from '@/lib/prisma';
import { getCurrentUser } from '@/lib/auth';
import { redirect } from 'next/navigation';
import { ArrowRight } from 'lucide-react';
import Link from 'next/link';

export default async function AuditorAssignmentsPage() {
  const user = await getCurrentUser();
  if (!user || !['ADMIN', 'SUPER_ADMIN', 'AUDITOR'].includes(user.role)) redirect('/login');
  const applications = await prisma.pengajuan.findMany({ where: user.role === 'AUDITOR' ? { assignments: { some: { auditorId: user.id } } } : { assignments: { some: {} } }, include: { assignments: { where: user.role === 'AUDITOR' ? { auditorId: user.id } : undefined, include: { auditor: { select: { name: true } } }, orderBy: { assignedAt: 'desc' } }, _count: { select: { products: true, ingredients: true, temuan: true } } }, orderBy: { updatedAt: 'desc' } });
  return <div className="space-y-6"><div><p className="mb-2 text-xs font-bold text-[#08725b]">Ruang Kerja Auditor</p><h1 className="display-font text-3xl font-extrabold tracking-[-.05em] text-[#10211e]">Assignment Saya</h1><p className="mt-1 text-sm text-[#71847f]">Daftar pengajuan yang dapat diperiksa oleh tim auditor.</p></div><section className="overflow-hidden rounded-2xl border border-[#e2eeeb] bg-white"><div className="border-b border-[#edf3f1] px-5 py-5"><h2 className="display-font font-bold text-[#183b34]">Daftar Assignment</h2></div>{applications.length === 0 ? <div className="p-12 text-center text-sm text-[#71847f]">Belum ada assignment audit.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-[#fbfdfc] text-[10px] font-bold text-[#8a9b97]"><tr><th className="px-5 py-3">Nomor Audit</th><th className="px-5 py-3">Perusahaan</th><th className="px-5 py-3">Auditor</th><th className="px-5 py-3">Data</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Aksi</th></tr></thead><tbody>{applications.map(item => { const assignment = item.assignments[0]; return <tr key={item.id} className="border-t border-[#edf3f1] text-[#526b66]"><td className="px-5 py-4 font-bold text-[#08725b]">{item.auditNumber}</td><td className="px-5 py-4 font-semibold text-[#234940]">{item.companyName}</td><td className="px-5 py-4">{assignment?.auditorName || assignment?.auditor.name || 'Tim auditor'}</td><td className="px-5 py-4">{item._count.products} produk · {item._count.ingredients} bahan</td><td className="px-5 py-4"><span className="rounded-full bg-[#fff4d7] px-2.5 py-1 text-[10px] font-bold text-[#a66a00]">{item.status.replaceAll('_', ' ')}</span></td><td className="px-5 py-4"><Link href={`/auditor/pengajuan/${item.id}/audit`} className="inline-flex items-center gap-1 rounded-lg bg-[#e7f5ef] px-3 py-1.5 text-[10px] font-bold text-[#08725b]">Buka Audit <ArrowRight size={12}/></Link></td></tr>; })}</tbody></table></div>}</section></div>;
}
