import { prisma } from '@/lib/prisma';
import { getCurrentUser } from '@/lib/auth';
import { redirect } from 'next/navigation';

export default async function AuditorHistoryPage() {
  const user = await getCurrentUser();
  if (!user || !['ADMIN', 'SUPER_ADMIN', 'AUDITOR'].includes(user.role)) redirect('/login');
  const applications = await prisma.pengajuan.findMany({ where: { status: 'SELESAI', ...(user.role === 'AUDITOR' ? { assignments: { some: { auditorId: user.id } } } : {}) }, include: { assignments: { where: user.role === 'AUDITOR' ? { auditorId: user.id } : undefined, include: { auditor: { select: { name: true } } }, orderBy: { assignedAt: 'desc' } } }, orderBy: { updatedAt: 'desc' } });
  return <div className="space-y-6"><div><p className="mb-2 text-xs font-bold text-[#08725b]">Ruang Kerja Auditor</p><h1 className="display-font text-3xl font-extrabold tracking-[-.05em] text-[#10211e]">Riwayat Audit</h1><p className="mt-1 text-sm text-[#71847f]">Audit yang telah diselesaikan oleh tim.</p></div><section className="overflow-hidden rounded-2xl border border-[#e2eeeb] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-[#fbfdfc] text-[10px] font-bold text-[#8a9b97]"><tr><th className="px-5 py-3">Nomor Audit</th><th className="px-5 py-3">Perusahaan</th><th className="px-5 py-3">Auditor</th><th className="px-5 py-3">Selesai</th><th className="px-5 py-3">Laporan</th></tr></thead><tbody>{applications.length === 0 ? <tr><td colSpan={5} className="p-12 text-center text-sm text-[#71847f]">Belum ada audit yang selesai.</td></tr> : applications.map(item => { const assignment = item.assignments[0]; return <tr key={item.id} className="border-t border-[#edf3f1] text-[#526b66]"><td className="px-5 py-4 font-bold text-[#08725b]">{item.auditNumber}</td><td className="px-5 py-4 font-semibold text-[#234940]">{item.companyName}</td><td className="px-5 py-4">{assignment ? `${assignment.auditorName || assignment.auditor.name}${assignment.auditorTitle ? `, ${assignment.auditorTitle}` : ''}` : 'Tim auditor'}</td><td className="px-5 py-4">{new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(item.updatedAt)}</td><td className="px-5 py-4"><a href={`/api/report/${item.id}`} className="font-bold text-[#08725b]">Download DOCX</a></td></tr>; })}</tbody></table></div></section></div>;
}
