import { prisma } from '@/lib/prisma';
import Link from 'next/link';
import { ArrowRight } from 'lucide-react';

const labels: Record<string, string> = { DRAFT: 'Draft', DIAJUKAN: 'Diajukan', MENUNGGU_REVIEW: 'Menunggu Review', MENUNGGU_AUDITOR: 'Menunggu Auditor', SEDANG_DIAUDIT: 'Sedang Audit', PERLU_PERBAIKAN: 'Perlu Perbaikan', MENUNGGU_VERIFIKASI: 'Menunggu Verifikasi', SELESAI: 'Selesai' };

export default async function AllApplicationsPage() {
  const applications = await prisma.pengajuan.findMany({ include: { user: true, _count: { select: { products: true, ingredients: true, temuan: true } } }, orderBy: { updatedAt: 'desc' } });
  return <div className="space-y-6"><div><p className="mb-2 text-xs font-bold text-[#08725b]">Administrasi LPH UNEJ</p><h1 className="display-font text-3xl font-extrabold tracking-[-.05em] text-[#10211e]">Seluruh Pengajuan</h1><p className="mt-1 text-sm text-[#71847f]">Kelola semua pengajuan sertifikasi yang masuk.</p></div><section className="overflow-hidden rounded-2xl border border-[#e2eeeb] bg-white"><div className="border-b border-[#edf3f1] px-5 py-5"><h2 className="display-font font-bold text-[#183b34]">Daftar Pengajuan</h2></div>{applications.length === 0 ? <div className="p-12 text-center text-sm text-[#71847f]">Belum ada pengajuan.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-[#fbfdfc] text-[10px] font-bold text-[#8a9b97]"><tr><th className="px-5 py-3">No. Audit</th><th className="px-5 py-3">Perusahaan</th><th className="px-5 py-3">Penyelia</th><th className="px-5 py-3">Produk / Bahan</th><th className="px-5 py-3">Temuan</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Aksi</th></tr></thead><tbody>{applications.map(item => <tr key={item.id} className="border-t border-[#edf3f1] text-[#526b66]"><td className="px-5 py-4 font-semibold text-[#08725b]">{item.auditNumber}</td><td className="px-5 py-4 font-semibold text-[#234940]">{item.companyName}</td><td className="px-5 py-4">{item.user.name}</td><td className="px-5 py-4">{item._count.products} / {item._count.ingredients}</td><td className="px-5 py-4">{item._count.temuan}</td><td className="px-5 py-4"><span className="rounded-full bg-[#fff4d7] px-2.5 py-1 text-[10px] font-bold text-[#a66a00]">{labels[item.status] ?? item.status}</span></td><td className="px-5 py-4"><Link href={`/admin/pengajuan/${item.id}`} className="inline-flex items-center gap-1 rounded-lg border border-[#dce9e5] px-3 py-1.5 text-[10px] font-bold text-[#45655d]">Detail <ArrowRight size={12}/></Link></td></tr>)}</tbody></table></div>}</section></div>;
}
